// @ts-check
/// <reference lib="dom" />
/* eslint-disable */
// Generated by openapi-fetch-client-gen. Do not edit by hand.

/**
 * @typedef {Object} Exercises
 * @property {number} id - Unique identifier for the exercise.
 * @property {string} name - Display name of the exercise (e.g., Pull Down).
 * @property {number} sort_order - Display order of the exercise in the workout UI.
 * @property {string} created_at - Timestamp when the exercise was added to the catalog.
 */

/**
 * @typedef {Object} ExercisesInsert
 * @property {number} id - Unique identifier for the exercise.
 * @property {string} name - Display name of the exercise (e.g., Pull Down).
 * @property {number} sort_order - Display order of the exercise in the workout UI.
 * @property {string} created_at - Timestamp when the exercise was added to the catalog.
 */

/**
 * @typedef {Object} ExercisesUpdate
 * @property {string} name - Display name of the exercise (e.g., Pull Down).
 * @property {number} sort_order - Display order of the exercise in the workout UI.
 * @property {string} created_at - Timestamp when the exercise was added to the catalog.
 */

/**
 * @typedef {Object} WorkoutExercises
 * @property {number} id - Unique identifier for the workout exercise entry.
 * @property {number} workout_id - Reference to the parent workout session.
 * @property {number} exercise_id - Reference to the exercise catalog entry.
 * @property {number} weight - Weight used in pounds (lbs).
 * @property {number} reps - Number of repetitions performed.
 * @property {number} time - Time under tension in seconds.
 */

/**
 * @typedef {Object} WorkoutExercisesInsert
 * @property {number} id - Unique identifier for the workout exercise entry.
 * @property {number} workout_id - Reference to the parent workout session.
 * @property {number} exercise_id - Reference to the exercise catalog entry.
 * @property {number} weight - Weight used in pounds (lbs).
 * @property {number} reps - Number of repetitions performed.
 * @property {number} time - Time under tension in seconds.
 */

/**
 * @typedef {Object} WorkoutExercisesUpdate
 * @property {number} workout_id - Reference to the parent workout session.
 * @property {number} exercise_id - Reference to the exercise catalog entry.
 * @property {number} weight - Weight used in pounds (lbs).
 * @property {number} reps - Number of repetitions performed.
 * @property {number} time - Time under tension in seconds.
 */

/**
 * @typedef {Object} Workouts
 * @property {number} id - Unique identifier for the workout session.
 * @property {string} started_at - When the user tapped Start Workout.
 * @property {string | null} ended_at - When the user tapped End Workout.
 * @property {number | null} total_gym_time - Total elapsed time at the gym in seconds.
 * @property {string} created_at - Timestamp when the workout record was persisted.
 */

/**
 * @typedef {Object} WorkoutsInsert
 * @property {number} id - Unique identifier for the workout session.
 * @property {string} started_at - When the user tapped Start Workout.
 * @property {string | null} ended_at - When the user tapped End Workout.
 * @property {number | null} total_gym_time - Total elapsed time at the gym in seconds.
 * @property {string} created_at - Timestamp when the workout record was persisted.
 */

/**
 * @typedef {Object} WorkoutsUpdate
 * @property {string} started_at - When the user tapped Start Workout.
 * @property {string | null} ended_at - When the user tapped End Workout.
 * @property {number | null} total_gym_time - Total elapsed time at the gym in seconds.
 * @property {string} created_at - Timestamp when the workout record was persisted.
 */


export class ApiClient {
  /**
   * @param {string} baseUrl
   */
  constructor(baseUrl) {
    this.baseUrl = baseUrl.replace(/\/?$/, "/");
  }

  /**
   * List exercises
   * @param {{ limit?: number, offset?: number }} params
   * @returns {Promise<Exercises[]>}
   */
  async listExercises(params = {}) {
    const url = new URL("exercises", this.baseUrl);
    const queryParams = new URLSearchParams();
    if (params.limit !== undefined) queryParams.append("limit", String(params.limit));
    if (params.offset !== undefined) queryParams.append("offset", String(params.offset));
    url.search = queryParams.toString();
    const response = await fetch(url.toString(), {
      method: "GET",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Create exercises
   * @param {{ body: ExercisesInsert }} params
   * @returns {Promise<Exercises>}
   */
  async createExercises(params) {
    const url = new URL("exercises", this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(params.body),
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Get a exercises by primary key
   * @param {{ pk_id: number }} params
   * @returns {Promise<Exercises>}
   */
  async getExercisesById(params) {
    const url = new URL(`exercises/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "GET",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Update exercises
   * @param {{ pk_id: number, body: ExercisesUpdate }} params
   * @returns {Promise<Exercises>}
   */
  async updateExercises(params) {
    const url = new URL(`exercises/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(params.body),
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Delete exercises
   * @param {{ pk_id: number }} params
   * @returns {Promise<void>}
   */
  async deleteExercises(params) {
    const url = new URL(`exercises/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return;
  }

  /**
   * List workout_exercises
   * @param {{ limit?: number, offset?: number }} params
   * @returns {Promise<WorkoutExercises[]>}
   */
  async listWorkoutExercises(params = {}) {
    const url = new URL("workout_exercises", this.baseUrl);
    const queryParams = new URLSearchParams();
    if (params.limit !== undefined) queryParams.append("limit", String(params.limit));
    if (params.offset !== undefined) queryParams.append("offset", String(params.offset));
    url.search = queryParams.toString();
    const response = await fetch(url.toString(), {
      method: "GET",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Create workout_exercises
   * @param {{ body: WorkoutExercisesInsert }} params
   * @returns {Promise<WorkoutExercises>}
   */
  async createWorkoutExercises(params) {
    const url = new URL("workout_exercises", this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(params.body),
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Get a workout_exercises by primary key
   * @param {{ pk_id: number }} params
   * @returns {Promise<WorkoutExercises>}
   */
  async getWorkoutExercisesById(params) {
    const url = new URL(`workout_exercises/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "GET",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Update workout_exercises
   * @param {{ pk_id: number, body: WorkoutExercisesUpdate }} params
   * @returns {Promise<WorkoutExercises>}
   */
  async updateWorkoutExercises(params) {
    const url = new URL(`workout_exercises/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(params.body),
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Delete workout_exercises
   * @param {{ pk_id: number }} params
   * @returns {Promise<void>}
   */
  async deleteWorkoutExercises(params) {
    const url = new URL(`workout_exercises/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return;
  }

  /**
   * List workouts
   * @param {{ limit?: number, offset?: number }} params
   * @returns {Promise<Workouts[]>}
   */
  async listWorkouts(params = {}) {
    const url = new URL("workouts", this.baseUrl);
    const queryParams = new URLSearchParams();
    if (params.limit !== undefined) queryParams.append("limit", String(params.limit));
    if (params.offset !== undefined) queryParams.append("offset", String(params.offset));
    url.search = queryParams.toString();
    const response = await fetch(url.toString(), {
      method: "GET",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Create workouts
   * @param {{ body: WorkoutsInsert }} params
   * @returns {Promise<Workouts>}
   */
  async createWorkouts(params) {
    const url = new URL("workouts", this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(params.body),
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Get a workouts by primary key
   * @param {{ pk_id: number }} params
   * @returns {Promise<Workouts>}
   */
  async getWorkoutsById(params) {
    const url = new URL(`workouts/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "GET",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Update workouts
   * @param {{ pk_id: number, body: WorkoutsUpdate }} params
   * @returns {Promise<Workouts>}
   */
  async updateWorkouts(params) {
    const url = new URL(`workouts/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(params.body),
    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return response.json();
  }

  /**
   * Delete workouts
   * @param {{ pk_id: number }} params
   * @returns {Promise<void>}
   */
  async deleteWorkouts(params) {
    const url = new URL(`workouts/${params.pk_id}`, this.baseUrl);

    const response = await fetch(url.toString(), {
      method: "DELETE",
      headers: { "Content-Type": "application/json" },

    });
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`HTTP ${response.status}: ${error}`);
    }
    return;
  }
}
